name: "semantic-pull-request"
description: "Semantic Pull Request"

inputs:
  github-access-token:
    description: "If the repository is private, specify a token."
    required: true

runs:
  using: "composite"
  steps:
    - name: Validate PR title
      uses: amannn/action-semantic-pull-request@v3.4.6
      with:
        # Comply with https://github.com/commitizen/conventional-commit-types/blob/c3a9be4c73e47f2e8197de775f41d981701407fb/index.json
        types: |
          feat
          fix
          docs
          style
          refactor
          perf
          test
          build
          ci
          chore
          revert
        subjectPattern: ^(?![A-Z]).+$
        validateSingleCommit: true
      env:
        GITHUB_TOKEN: ${{ inputs.github-access-token }}
